# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shop_game_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_shop_info(object):
    def setupUi(self, shop_info):
        shop_info.setObjectName("shop_info")
        shop_info.resize(702, 468)
        self.verticalLayout = QtWidgets.QVBoxLayout(shop_info)
        self.verticalLayout.setObjectName("verticalLayout")
        self.back_button = QtWidgets.QPushButton(shop_info)
        self.back_button.setObjectName("back_button")
        self.verticalLayout.addWidget(self.back_button)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image = QtWidgets.QLabel(shop_info)
        self.image.setObjectName("image")
        self.horizontalLayout.addWidget(self.image)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title = QtWidgets.QLabel(shop_info)
        self.title.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.title.setObjectName("title")
        self.verticalLayout_2.addWidget(self.title)
        self.dev = QtWidgets.QLabel(shop_info)
        self.dev.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.dev.setObjectName("dev")
        self.verticalLayout_2.addWidget(self.dev)
        self.price = QtWidgets.QLabel(shop_info)
        self.price.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.price.setObjectName("price")
        self.verticalLayout_2.addWidget(self.price)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.open_store_button = QtWidgets.QPushButton(shop_info)
        self.open_store_button.setObjectName("open_store_button")
        self.verticalLayout.addWidget(self.open_store_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(shop_info)
        QtCore.QMetaObject.connectSlotsByName(shop_info)

    def retranslateUi(self, shop_info):
        _translate = QtCore.QCoreApplication.translate
        shop_info.setWindowTitle(_translate("shop_info", "Form"))
        self.back_button.setText(_translate("shop_info", "Back"))
        self.image.setText(_translate("shop_info", "TextLabel"))
        self.title.setText(_translate("shop_info", "Error"))
        self.dev.setText(_translate("shop_info", "TextLabel"))
        self.price.setText(_translate("shop_info", "TextLabel"))
        self.open_store_button.setText(_translate("shop_info", "Buy Game in Epic Games Store"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    shop_info = QtWidgets.QWidget()
    ui = Ui_shop_info()
    ui.setupUi(shop_info)
    shop_info.show()
    sys.exit(app.exec_())
