# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rare/ui/components/tabs/store/shop_game_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShopGameInfo(object):
    def setupUi(self, ShopGameInfo):
        ShopGameInfo.setObjectName("ShopGameInfo")
        ShopGameInfo.resize(702, 468)
        ShopGameInfo.setWindowTitle("ShopGameInfo")
        self.shop_game_info_layout = QtWidgets.QVBoxLayout(ShopGameInfo)
        self.shop_game_info_layout.setObjectName("shop_game_info_layout")
        self.image_info_layout = QtWidgets.QHBoxLayout()
        self.image_info_layout.setObjectName("image_info_layout")
        self.info_layout = QtWidgets.QGridLayout()
        self.info_layout.setObjectName("info_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.info_layout.addItem(spacerItem, 6, 1, 1, 1)
        self.tags = QtWidgets.QLabel(ShopGameInfo)
        self.tags.setText("tags")
        self.tags.setObjectName("tags")
        self.info_layout.addWidget(self.tags, 5, 0, 1, 2)
        self.discount_price = QtWidgets.QLabel(ShopGameInfo)
        self.discount_price.setText("discount")
        self.discount_price.setObjectName("discount_price")
        self.info_layout.addWidget(self.discount_price, 4, 0, 1, 2)
        self.title = QtWidgets.QLabel(ShopGameInfo)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.title.setFont(font)
        self.title.setText("title")
        self.title.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.title.setObjectName("title")
        self.info_layout.addWidget(self.title, 0, 0, 1, 2)
        self.button_layout = QtWidgets.QVBoxLayout()
        self.button_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.button_layout.setObjectName("button_layout")
        self.open_store_button = QtWidgets.QPushButton(ShopGameInfo)
        self.open_store_button.setObjectName("open_store_button")
        self.button_layout.addWidget(self.open_store_button)
        self.wishlist_button = QtWidgets.QPushButton(ShopGameInfo)
        self.wishlist_button.setObjectName("wishlist_button")
        self.button_layout.addWidget(self.wishlist_button)
        self.info_layout.addLayout(self.button_layout, 6, 0, 1, 1)
        self.dev = QtWidgets.QLabel(ShopGameInfo)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dev.setFont(font)
        self.dev.setText("dev")
        self.dev.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.dev.setObjectName("dev")
        self.info_layout.addWidget(self.dev, 1, 0, 1, 2)
        self.owned_label = QtWidgets.QLabel(ShopGameInfo)
        self.owned_label.setObjectName("owned_label")
        self.info_layout.addWidget(self.owned_label, 2, 0, 1, 2)
        self.price = QtWidgets.QLabel(ShopGameInfo)
        self.price.setText("price")
        self.price.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.price.setObjectName("price")
        self.info_layout.addWidget(self.price, 3, 0, 1, 2)
        self.social_group = QtWidgets.QGroupBox(ShopGameInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.social_group.sizePolicy().hasHeightForWidth())
        self.social_group.setSizePolicy(sizePolicy)
        self.social_group.setObjectName("social_group")
        self.social_layout = QtWidgets.QHBoxLayout(self.social_group)
        self.social_layout.setObjectName("social_layout")
        self.info_layout.addWidget(self.social_group, 7, 0, 1, 2)
        self.image_info_layout.addLayout(self.info_layout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.image_info_layout.addItem(spacerItem1)
        self.shop_game_info_layout.addLayout(self.image_info_layout)
        self.requirements_group = QtWidgets.QGroupBox(ShopGameInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.requirements_group.sizePolicy().hasHeightForWidth())
        self.requirements_group.setSizePolicy(sizePolicy)
        self.requirements_group.setObjectName("requirements_group")
        self.requirements_layout = QtWidgets.QHBoxLayout(self.requirements_group)
        self.requirements_layout.setContentsMargins(0, 0, 0, 0)
        self.requirements_layout.setObjectName("requirements_layout")
        self.shop_game_info_layout.addWidget(self.requirements_group)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.shop_game_info_layout.addItem(spacerItem2)

        self.retranslateUi(ShopGameInfo)

    def retranslateUi(self, ShopGameInfo):
        _translate = QtCore.QCoreApplication.translate
        self.open_store_button.setText(_translate("ShopGameInfo", "Buy in Epic Games Store"))
        self.wishlist_button.setText(_translate("ShopGameInfo", "Add to wishlist"))
        self.owned_label.setText(_translate("ShopGameInfo", "You already own this game"))
        self.social_group.setTitle(_translate("ShopGameInfo", "Links"))
        self.requirements_group.setTitle(_translate("ShopGameInfo", "System requirements"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ShopGameInfo = QtWidgets.QWidget()
    ui = Ui_ShopGameInfo()
    ui.setupUi(ShopGameInfo)
    ShopGameInfo.show()
    sys.exit(app.exec_())
