# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'store.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShopWidget(object):
    def setupUi(self, ShopWidget):
        ShopWidget.setObjectName("ShopWidget")
        ShopWidget.resize(697, 362)
        self.verticalLayout = QtWidgets.QVBoxLayout(ShopWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search = QtWidgets.QLineEdit(ShopWidget)
        self.search.setObjectName("search")
        self.verticalLayout.addWidget(self.search)
        self.free_game_group_box = QtWidgets.QGroupBox(ShopWidget)
        self.free_game_group_box.setObjectName("free_game_group_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.free_game_group_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.free_games_stack = QtWidgets.QStackedWidget(self.free_game_group_box)
        self.free_games_stack.setObjectName("free_games_stack")
        self.verticalLayout_2.addWidget(self.free_games_stack)
        self.verticalLayout.addWidget(self.free_game_group_box)
        self.games_groupbox = QtWidgets.QGroupBox(ShopWidget)
        self.games_groupbox.setObjectName("games_groupbox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.games_groupbox)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout.addWidget(self.games_groupbox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(ShopWidget)
        self.free_games_stack.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(ShopWidget)

    def retranslateUi(self, ShopWidget):
        _translate = QtCore.QCoreApplication.translate
        ShopWidget.setWindowTitle(_translate("ShopWidget", "Form"))
        self.search.setPlaceholderText(_translate("ShopWidget", "Search Games"))
        self.free_game_group_box.setTitle(_translate("ShopWidget", "Free Games"))
        self.games_groupbox.setTitle(_translate("ShopWidget", "Other nice games"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ShopWidget = QtWidgets.QWidget()
    ui = Ui_ShopWidget()
    ui.setupUi(ShopWidget)
    ShopWidget.show()
    sys.exit(app.exec_())
