# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'store.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShopWidget(object):
    def setupUi(self, ShopWidget):
        ShopWidget.setObjectName("ShopWidget")
        ShopWidget.resize(697, 362)
        self.verticalLayout = QtWidgets.QVBoxLayout(ShopWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search = QtWidgets.QLineEdit(ShopWidget)
        self.search.setObjectName("search")
        self.verticalLayout.addWidget(self.search)
        self.search_results = QtWidgets.QGroupBox(ShopWidget)
        self.search_results.setFlat(False)
        self.search_results.setObjectName("search_results")
        self.verticalLayout.addWidget(self.search_results)
        self.free_game_group_box_2 = QtWidgets.QGroupBox(ShopWidget)
        self.free_game_group_box_2.setObjectName("free_game_group_box_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.free_game_group_box_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.free_games_stack = QtWidgets.QStackedWidget(self.free_game_group_box_2)
        self.free_games_stack.setObjectName("free_games_stack")
        self.free_games_page = QtWidgets.QWidget()
        self.free_games_page.setObjectName("free_games_page")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.free_games_page)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.free_game_now = QtWidgets.QGroupBox(self.free_games_page)
        self.free_game_now.setObjectName("free_game_now")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.free_game_now)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3.addWidget(self.free_game_now)
        self.comming_free_game = QtWidgets.QGroupBox(self.free_games_page)
        self.comming_free_game.setObjectName("comming_free_game")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.comming_free_game)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3.addWidget(self.comming_free_game)
        self.free_games_stack.addWidget(self.free_games_page)
        self.verticalLayout_2.addWidget(self.free_games_stack)
        self.verticalLayout.addWidget(self.free_game_group_box_2)
        self.games_groupbox_2 = QtWidgets.QGroupBox(ShopWidget)
        self.games_groupbox_2.setObjectName("games_groupbox_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.games_groupbox_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout.addWidget(self.games_groupbox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(ShopWidget)
        self.free_games_stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ShopWidget)

    def retranslateUi(self, ShopWidget):
        _translate = QtCore.QCoreApplication.translate
        ShopWidget.setWindowTitle(_translate("ShopWidget", "Form"))
        self.search.setPlaceholderText(_translate("ShopWidget", "Search Games"))
        self.search_results.setTitle(_translate("ShopWidget", "Search results"))
        self.free_game_group_box_2.setTitle(_translate("ShopWidget", "Free Games"))
        self.free_game_now.setTitle(_translate("ShopWidget", "Free Game"))
        self.comming_free_game.setTitle(_translate("ShopWidget", "Comming Free Game"))
        self.games_groupbox_2.setTitle(_translate("ShopWidget", "Other nice games"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ShopWidget = QtWidgets.QWidget()
    ui = Ui_ShopWidget()
    ui.setupUi(ShopWidget)
    ShopWidget.show()
    sys.exit(app.exec_())
