# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rare/ui/components/tabs/store/wishlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wishlist(object):
    def setupUi(self, Wishlist):
        Wishlist.setObjectName("Wishlist")
        Wishlist.resize(489, 165)
        Wishlist.setWindowTitle("Wishlist")
        self.main_layout = QtWidgets.QVBoxLayout(Wishlist)
        self.main_layout.setObjectName("main_layout")
        self.tool_layout = QtWidgets.QHBoxLayout()
        self.tool_layout.setObjectName("tool_layout")
        self.filter_combo = QtWidgets.QComboBox(Wishlist)
        self.filter_combo.setObjectName("filter_combo")
        self.tool_layout.addWidget(self.filter_combo)
        self.order_combo = QtWidgets.QComboBox(Wishlist)
        self.order_combo.setObjectName("order_combo")
        self.tool_layout.addWidget(self.order_combo)
        self.reverse_check = QtWidgets.QCheckBox(Wishlist)
        self.reverse_check.setObjectName("reverse_check")
        self.tool_layout.addWidget(self.reverse_check)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.tool_layout.addItem(spacerItem)
        self.reload_button = QtWidgets.QPushButton(Wishlist)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reload_button.sizePolicy().hasHeightForWidth())
        self.reload_button.setSizePolicy(sizePolicy)
        self.reload_button.setText("")
        self.reload_button.setObjectName("reload_button")
        self.tool_layout.addWidget(self.reload_button)
        self.main_layout.addLayout(self.tool_layout)
        self.scrollarea = QtWidgets.QScrollArea(Wishlist)
        self.scrollarea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollarea.setWidgetResizable(True)
        self.scrollarea.setObjectName("scrollarea")
        self.container = QtWidgets.QWidget()
        self.container.setGeometry(QtCore.QRect(0, 0, 473, 115))
        self.container.setObjectName("container")
        self.container_layout = QtWidgets.QVBoxLayout(self.container)
        self.container_layout.setObjectName("container_layout")
        self.no_games_label = QtWidgets.QLabel(self.container)
        self.no_games_label.setObjectName("no_games_label")
        self.container_layout.addWidget(self.no_games_label, 0, QtCore.Qt.AlignTop)
        self.scrollarea.setWidget(self.container)
        self.main_layout.addWidget(self.scrollarea)

        self.retranslateUi(Wishlist)

    def retranslateUi(self, Wishlist):
        _translate = QtCore.QCoreApplication.translate
        self.reverse_check.setText(_translate("Wishlist", "Reverse"))
        self.no_games_label.setText(_translate("Wishlist", "No games matching your filter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wishlist = QtWidgets.QWidget()
    ui = Ui_Wishlist()
    ui.setupUi(Wishlist)
    Wishlist.show()
    sys.exit(app.exec_())
