# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rare/ui/components/tabs/store/wishlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wishlist(object):
    def setupUi(self, Wishlist):
        Wishlist.setObjectName("Wishlist")
        Wishlist.resize(423, 153)
        Wishlist.setWindowTitle("Wishlist")
        self.verticalLayout = QtWidgets.QVBoxLayout(Wishlist)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tool_layout = QtWidgets.QHBoxLayout()
        self.tool_layout.setObjectName("tool_layout")
        self.sort_label = QtWidgets.QLabel(Wishlist)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sort_label.sizePolicy().hasHeightForWidth())
        self.sort_label.setSizePolicy(sizePolicy)
        self.sort_label.setObjectName("sort_label")
        self.tool_layout.addWidget(self.sort_label)
        self.sort_cb = QtWidgets.QComboBox(Wishlist)
        self.sort_cb.setObjectName("sort_cb")
        self.sort_cb.addItem("")
        self.sort_cb.addItem("")
        self.sort_cb.addItem("")
        self.sort_cb.addItem("")
        self.tool_layout.addWidget(self.sort_cb)
        self.reverse = QtWidgets.QCheckBox(Wishlist)
        self.reverse.setObjectName("reverse")
        self.tool_layout.addWidget(self.reverse)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.tool_layout.addItem(spacerItem)
        self.filter_label = QtWidgets.QLabel(Wishlist)
        self.filter_label.setObjectName("filter_label")
        self.tool_layout.addWidget(self.filter_label)
        self.filter_cb = QtWidgets.QComboBox(Wishlist)
        self.filter_cb.setObjectName("filter_cb")
        self.filter_cb.addItem("")
        self.filter_cb.addItem("")
        self.tool_layout.addWidget(self.filter_cb)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.tool_layout.addItem(spacerItem1)
        self.reload_button = QtWidgets.QPushButton(Wishlist)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reload_button.sizePolicy().hasHeightForWidth())
        self.reload_button.setSizePolicy(sizePolicy)
        self.reload_button.setText("")
        self.reload_button.setObjectName("reload_button")
        self.tool_layout.addWidget(self.reload_button)
        self.verticalLayout.addLayout(self.tool_layout)
        self.no_games_label = QtWidgets.QLabel(Wishlist)
        self.no_games_label.setObjectName("no_games_label")
        self.verticalLayout.addWidget(self.no_games_label)
        self.list_scrollarea = QtWidgets.QScrollArea(Wishlist)
        self.list_scrollarea.setWidgetResizable(True)
        self.list_scrollarea.setObjectName("list_scrollarea")
        self.list_container = QtWidgets.QWidget()
        self.list_container.setGeometry(QtCore.QRect(0, 0, 407, 83))
        self.list_container.setObjectName("list_container")
        self.list_scrollarea.setWidget(self.list_container)
        self.verticalLayout.addWidget(self.list_scrollarea)

        self.retranslateUi(Wishlist)

    def retranslateUi(self, Wishlist):
        _translate = QtCore.QCoreApplication.translate
        self.sort_label.setText(_translate("Wishlist", "Sort by"))
        self.sort_cb.setItemText(0, _translate("Wishlist", "Name"))
        self.sort_cb.setItemText(1, _translate("Wishlist", "Price"))
        self.sort_cb.setItemText(2, _translate("Wishlist", "Developer"))
        self.sort_cb.setItemText(3, _translate("Wishlist", "Discount"))
        self.reverse.setText(_translate("Wishlist", "Reverse"))
        self.filter_label.setText(_translate("Wishlist", "Filter:"))
        self.filter_cb.setItemText(0, _translate("Wishlist", "None"))
        self.filter_cb.setItemText(1, _translate("Wishlist", "Discount"))
        self.no_games_label.setText(_translate("Wishlist", "No games matching your filter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wishlist = QtWidgets.QWidget()
    ui = Ui_Wishlist()
    ui.setupUi(Wishlist)
    Wishlist.show()
    sys.exit(app.exec_())
