# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rare/ui/components/tabs/games/env_vars.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_env_vars_groupbox(object):
    def setupUi(self, env_vars_groupbox):
        env_vars_groupbox.setObjectName("env_vars_groupbox")
        env_vars_groupbox.resize(720, 561)
        env_vars_groupbox.setMinimumSize(QtCore.QSize(200, 200))
        self.verticalLayout = QtWidgets.QVBoxLayout(env_vars_groupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.env_vars_table = QtWidgets.QTableWidget(env_vars_groupbox)
        self.env_vars_table.setMinimumSize(QtCore.QSize(0, 500))
        self.env_vars_table.setObjectName("env_vars_table")
        self.env_vars_table.setColumnCount(2)
        self.env_vars_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.env_vars_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.env_vars_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.env_vars_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.env_vars_table)

        self.retranslateUi(env_vars_groupbox)
        QtCore.QMetaObject.connectSlotsByName(env_vars_groupbox)

    def retranslateUi(self, env_vars_groupbox):
        _translate = QtCore.QCoreApplication.translate
        env_vars_groupbox.setWindowTitle(_translate("env_vars_groupbox", "GroupBox"))
        env_vars_groupbox.setTitle(_translate("env_vars_groupbox", "Environment variables"))
        item = self.env_vars_table.verticalHeaderItem(0)
        item.setText(_translate("env_vars_groupbox", "-"))
        item = self.env_vars_table.horizontalHeaderItem(0)
        item.setText(_translate("env_vars_groupbox", "Key"))
        item = self.env_vars_table.horizontalHeaderItem(1)
        item.setText(_translate("env_vars_groupbox", "Value"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    env_vars_groupbox = QtWidgets.QGroupBox()
    ui = Ui_env_vars_groupbox()
    ui.setupUi(env_vars_groupbox)
    env_vars_groupbox.show()
    sys.exit(app.exec_())
