# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rare/ui/components/tabs/games/games_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GamesTab(object):
    def setupUi(self, GamesTab):
        GamesTab.setObjectName("GamesTab")
        GamesTab.resize(104, 42)
        GamesTab.setWindowTitle("StackedWidget")
        self.games = QtWidgets.QWidget()
        self.games.setObjectName("games")
        self.games_layout = QtWidgets.QVBoxLayout(self.games)
        self.games_layout.setObjectName("games_layout")
        self.library_frame = QtWidgets.QFrame(self.games)
        self.library_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.library_frame.setObjectName("library_frame")
        self.library_frame_layout = QtWidgets.QVBoxLayout(self.library_frame)
        self.library_frame_layout.setContentsMargins(0, 0, 0, 0)
        self.library_frame_layout.setObjectName("library_frame_layout")
        self.count_games_layout = QtWidgets.QHBoxLayout()
        self.count_games_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.count_games_layout.setContentsMargins(6, 6, 6, 6)
        self.count_games_layout.setObjectName("count_games_layout")
        self.count_games_label = QtWidgets.QLabel(self.library_frame)
        self.count_games_label.setText("error")
        self.count_games_label.setObjectName("count_games_label")
        self.count_games_layout.addWidget(self.count_games_label, 0, QtCore.Qt.AlignTop)
        self.library_frame_layout.addLayout(self.count_games_layout)
        self.games_layout.addWidget(self.library_frame)
        self.games_layout.setStretch(0, 1)
        GamesTab.addWidget(self.games)

        self.retranslateUi(GamesTab)
        GamesTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GamesTab)

    def retranslateUi(self, GamesTab):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GamesTab = QtWidgets.QStackedWidget()
    ui = Ui_GamesTab()
    ui.setupUi(GamesTab)
    GamesTab.show()
    sys.exit(app.exec_())
