# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/components/tabs/settings/linux.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LinuxSettings(object):
    def setupUi(self, LinuxSettings):
        LinuxSettings.setObjectName("LinuxSettings")
        LinuxSettings.resize(569, 454)
        self.layout_linux = QtWidgets.QGridLayout(LinuxSettings)
        self.layout_linux.setObjectName("layout_linux")
        self.layout_dxvk = QtWidgets.QVBoxLayout()
        self.layout_dxvk.setObjectName("layout_dxvk")
        self.layout_linux.addLayout(self.layout_dxvk, 2, 0, 1, 1)
        self.gb_wine = QtWidgets.QGroupBox(LinuxSettings)
        self.gb_wine.setObjectName("gb_wine")
        self.layout_wine = QtWidgets.QGridLayout(self.gb_wine)
        self.layout_wine.setObjectName("layout_wine")
        self.lbl_exec = QtWidgets.QLabel(self.gb_wine)
        self.lbl_exec.setObjectName("lbl_exec")
        self.layout_wine.addWidget(self.lbl_exec, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lbl_prefix = QtWidgets.QLabel(self.gb_wine)
        self.lbl_prefix.setObjectName("lbl_prefix")
        self.layout_wine.addWidget(self.lbl_prefix, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.frame_prefix = QtWidgets.QFrame(self.gb_wine)
        self.frame_prefix.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_prefix.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_prefix.setObjectName("frame_prefix")
        self.layout_prefix = QtWidgets.QVBoxLayout(self.frame_prefix)
        self.layout_prefix.setObjectName("layout_prefix")
        self.layout_wine.addWidget(self.frame_prefix, 0, 1, 1, 1)
        self.frame_exec = QtWidgets.QFrame(self.gb_wine)
        self.frame_exec.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_exec.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_exec.setObjectName("frame_exec")
        self.layout_exec = QtWidgets.QVBoxLayout(self.frame_exec)
        self.layout_exec.setObjectName("layout_exec")
        self.layout_wine.addWidget(self.frame_exec, 1, 1, 1, 1)
        self.layout_linux.addWidget(self.gb_wine, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_linux.addItem(spacerItem, 4, 0, 1, 1)
        self.layout_proton = QtWidgets.QVBoxLayout()
        self.layout_proton.setObjectName("layout_proton")
        self.layout_linux.addLayout(self.layout_proton, 1, 0, 1, 1)

        self.retranslateUi(LinuxSettings)
        QtCore.QMetaObject.connectSlotsByName(LinuxSettings)

    def retranslateUi(self, LinuxSettings):
        _translate = QtCore.QCoreApplication.translate
        LinuxSettings.setWindowTitle(_translate("LinuxSettings", "LinuxSettings"))
        self.gb_wine.setTitle(_translate("LinuxSettings", "Wine Settings"))
        self.lbl_exec.setText(_translate("LinuxSettings", "Wine executable:"))
        self.lbl_prefix.setText(_translate("LinuxSettings", "Wine prefix:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LinuxSettings = QtWidgets.QWidget()
    ui = Ui_LinuxSettings()
    ui.setupUi(LinuxSettings)
    LinuxSettings.show()
    sys.exit(app.exec_())
