# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/components/tabs/settings/rare.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RareSettings(object):
    def setupUi(self, RareSettings):
        RareSettings.setObjectName("RareSettings")
        RareSettings.resize(633, 480)
        self.gridLayout = QtWidgets.QGridLayout(RareSettings)
        self.gridLayout.setObjectName("gridLayout")
        self.img_dir_ph = QtWidgets.QWidget(RareSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_dir_ph.sizePolicy().hasHeightForWidth())
        self.img_dir_ph.setSizePolicy(sizePolicy)
        self.img_dir_ph.setObjectName("img_dir_ph")
        self.gridLayout.addWidget(self.img_dir_ph, 0, 0, 1, 1)
        self.settings_widget_ph = QtWidgets.QWidget(RareSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_widget_ph.sizePolicy().hasHeightForWidth())
        self.settings_widget_ph.setSizePolicy(sizePolicy)
        self.settings_widget_ph.setObjectName("settings_widget_ph")
        self.gridLayout.addWidget(self.settings_widget_ph, 1, 0, 1, 1)
        self.rpc_ph = QtWidgets.QWidget(RareSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rpc_ph.sizePolicy().hasHeightForWidth())
        self.rpc_ph.setSizePolicy(sizePolicy)
        self.rpc_ph.setObjectName("rpc_ph")
        self.gridLayout.addWidget(self.rpc_ph, 1, 1, 1, 1)
        self.lang_widget_ph = QtWidgets.QWidget(RareSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lang_widget_ph.sizePolicy().hasHeightForWidth())
        self.lang_widget_ph.setSizePolicy(sizePolicy)
        self.lang_widget_ph.setObjectName("lang_widget_ph")
        self.gridLayout.addWidget(self.lang_widget_ph, 0, 1, 1, 1)

        self.retranslateUi(RareSettings)
        QtCore.QMetaObject.connectSlotsByName(RareSettings)

    def retranslateUi(self, RareSettings):
        _translate = QtCore.QCoreApplication.translate
        RareSettings.setWindowTitle(_translate("RareSettings", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RareSettings = QtWidgets.QWidget()
    ui = Ui_RareSettings()
    ui.setupUi(RareSettings)
    RareSettings.show()
    sys.exit(app.exec_())
