# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rare/ui/components/tabs/games/game_info/cloud_sync_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CloudSyncWidget(object):
    def setupUi(self, CloudSyncWidget):
        CloudSyncWidget.setObjectName("CloudSyncWidget")
        CloudSyncWidget.resize(438, 137)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CloudSyncWidget.sizePolicy().hasHeightForWidth())
        CloudSyncWidget.setSizePolicy(sizePolicy)
        CloudSyncWidget.setWindowTitle("SyncWidget")
        self.main_layout = QtWidgets.QHBoxLayout(CloudSyncWidget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.local_group = QtWidgets.QGroupBox(CloudSyncWidget)
        self.local_group.setObjectName("local_group")
        self.local_layout = QtWidgets.QVBoxLayout(self.local_group)
        self.local_layout.setObjectName("local_layout")
        self.date_info_local = QtWidgets.QLabel(self.local_group)
        self.date_info_local.setText("")
        self.date_info_local.setAlignment(QtCore.Qt.AlignCenter)
        self.date_info_local.setObjectName("date_info_local")
        self.local_layout.addWidget(self.date_info_local)
        self.icon_local = QtWidgets.QLabel(self.local_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_local.sizePolicy().hasHeightForWidth())
        self.icon_local.setSizePolicy(sizePolicy)
        self.icon_local.setText("")
        self.icon_local.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_local.setObjectName("icon_local")
        self.local_layout.addWidget(self.icon_local)
        self.age_label_local = QtWidgets.QLabel(self.local_group)
        self.age_label_local.setText("")
        self.age_label_local.setAlignment(QtCore.Qt.AlignCenter)
        self.age_label_local.setObjectName("age_label_local")
        self.local_layout.addWidget(self.age_label_local)
        self.upload_button = QtWidgets.QPushButton(self.local_group)
        self.upload_button.setMinimumSize(QtCore.QSize(192, 0))
        self.upload_button.setObjectName("upload_button")
        self.local_layout.addWidget(self.upload_button)
        self.main_layout.addWidget(self.local_group)
        self.cloud_group = QtWidgets.QGroupBox(CloudSyncWidget)
        self.cloud_group.setObjectName("cloud_group")
        self.cloud_layout = QtWidgets.QVBoxLayout(self.cloud_group)
        self.cloud_layout.setObjectName("cloud_layout")
        self.date_info_remote = QtWidgets.QLabel(self.cloud_group)
        self.date_info_remote.setText("")
        self.date_info_remote.setAlignment(QtCore.Qt.AlignCenter)
        self.date_info_remote.setObjectName("date_info_remote")
        self.cloud_layout.addWidget(self.date_info_remote)
        self.icon_remote = QtWidgets.QLabel(self.cloud_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_remote.sizePolicy().hasHeightForWidth())
        self.icon_remote.setSizePolicy(sizePolicy)
        self.icon_remote.setText("")
        self.icon_remote.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_remote.setObjectName("icon_remote")
        self.cloud_layout.addWidget(self.icon_remote)
        self.age_label_remote = QtWidgets.QLabel(self.cloud_group)
        self.age_label_remote.setText("")
        self.age_label_remote.setAlignment(QtCore.Qt.AlignCenter)
        self.age_label_remote.setObjectName("age_label_remote")
        self.cloud_layout.addWidget(self.age_label_remote)
        self.download_button = QtWidgets.QPushButton(self.cloud_group)
        self.download_button.setMinimumSize(QtCore.QSize(192, 0))
        self.download_button.setObjectName("download_button")
        self.cloud_layout.addWidget(self.download_button)
        self.main_layout.addWidget(self.cloud_group)

        self.retranslateUi(CloudSyncWidget)

    def retranslateUi(self, CloudSyncWidget):
        _translate = QtCore.QCoreApplication.translate
        self.local_group.setTitle(_translate("CloudSyncWidget", "Local"))
        self.upload_button.setText(_translate("CloudSyncWidget", "Upload"))
        self.cloud_group.setTitle(_translate("CloudSyncWidget", "Cloud"))
        self.download_button.setText(_translate("CloudSyncWidget", "Download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CloudSyncWidget = QtWidgets.QWidget()
    ui = Ui_CloudSyncWidget()
    ui.setupUi(CloudSyncWidget)
    CloudSyncWidget.show()
    sys.exit(app.exec_())
