# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rare/ui/components/tabs/games/game_info/cloud_saves.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CloudSaves(object):
    def setupUi(self, CloudSaves):
        CloudSaves.setObjectName("CloudSaves")
        CloudSaves.resize(580, 300)
        CloudSaves.setWindowTitle("Form")
        self.verticalLayout = QtWidgets.QVBoxLayout(CloudSaves)
        self.verticalLayout.setObjectName("verticalLayout")
        self.game_title = QtWidgets.QLabel(CloudSaves)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_title.sizePolicy().hasHeightForWidth())
        self.game_title.setSizePolicy(sizePolicy)
        self.game_title.setObjectName("game_title")
        self.verticalLayout.addWidget(self.game_title)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cloud_info_label = QtWidgets.QLabel(CloudSaves)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cloud_info_label.sizePolicy().hasHeightForWidth())
        self.cloud_info_label.setSizePolicy(sizePolicy)
        self.cloud_info_label.setMinimumSize(QtCore.QSize(115, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cloud_info_label.setFont(font)
        self.cloud_info_label.setObjectName("cloud_info_label")
        self.gridLayout.addWidget(self.cloud_info_label, 0, 0, 1, 1)
        self.local_text_label = QtWidgets.QLabel(CloudSaves)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.local_text_label.sizePolicy().hasHeightForWidth())
        self.local_text_label.setSizePolicy(sizePolicy)
        self.local_text_label.setMinimumSize(QtCore.QSize(112, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.local_text_label.setFont(font)
        self.local_text_label.setObjectName("local_text_label")
        self.gridLayout.addWidget(self.local_text_label, 1, 0, 1, 1)
        self.cloud_label = QtWidgets.QLabel(CloudSaves)
        self.cloud_label.setText("No save online")
        self.cloud_label.setObjectName("cloud_label")
        self.gridLayout.addWidget(self.cloud_label, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.local_label = QtWidgets.QLabel(CloudSaves)
        self.local_label.setText("No local save")
        self.local_label.setObjectName("local_label")
        self.gridLayout.addWidget(self.local_label, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.verticalLayout.addLayout(self.gridLayout)
        self.pathlayout = QtWidgets.QVBoxLayout()
        self.pathlayout.setObjectName("pathlayout")
        self.verticalLayout.addLayout(self.pathlayout)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        self.download_button = QtWidgets.QPushButton(CloudSaves)
        self.download_button.setText("Download")
        self.download_button.setObjectName("download_button")
        self.button_layout.addWidget(self.download_button)
        self.upload_button = QtWidgets.QPushButton(CloudSaves)
        self.upload_button.setText("Upload")
        self.upload_button.setObjectName("upload_button")
        self.button_layout.addWidget(self.upload_button)
        self.verticalLayout.addLayout(self.button_layout)
        self.clean_saves_button = QtWidgets.QPushButton(CloudSaves)
        self.clean_saves_button.setObjectName("clean_saves_button")
        self.verticalLayout.addWidget(self.clean_saves_button)
        self.info_label = QtWidgets.QLabel(CloudSaves)
        self.info_label.setText("")
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.info_label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(CloudSaves)
        QtCore.QMetaObject.connectSlotsByName(CloudSaves)

    def retranslateUi(self, CloudSaves):
        _translate = QtCore.QCoreApplication.translate
        self.game_title.setText(_translate("CloudSaves", "TextLabel"))
        self.cloud_info_label.setText(_translate("CloudSaves", "Cloud Save date:"))
        self.local_text_label.setText(_translate("CloudSaves", "Local Save date:"))
        self.clean_saves_button.setText(_translate("CloudSaves", "Clean saves"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    CloudSaves = QtWidgets.QWidget()
    ui = Ui_CloudSaves()
    ui.setupUi(CloudSaves)
    CloudSaves.show()
    sys.exit(app.exec_())
