# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rare/ui/components/tabs/games/game_info/cloud_settings_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CloudSettingsWidget(object):
    def setupUi(self, CloudSettingsWidget):
        CloudSettingsWidget.setObjectName("CloudSettingsWidget")
        CloudSettingsWidget.resize(388, 78)
        CloudSettingsWidget.setWindowTitle("CloudSettingsWidget")
        self.main_layout = QtWidgets.QFormLayout(CloudSettingsWidget)
        self.main_layout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.main_layout.setObjectName("main_layout")
        self.sync_label = QtWidgets.QLabel(CloudSettingsWidget)
        self.sync_label.setObjectName("sync_label")
        self.main_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sync_label)
        self.sync_check = QtWidgets.QCheckBox(CloudSettingsWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.sync_check.setFont(font)
        self.sync_check.setText("Automatically synchronize saves with the cloud")
        self.sync_check.setObjectName("sync_check")
        self.main_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sync_check)
        self.path_label = QtWidgets.QLabel(CloudSettingsWidget)
        self.path_label.setObjectName("path_label")
        self.main_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.path_label)

        self.retranslateUi(CloudSettingsWidget)

    def retranslateUi(self, CloudSettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        CloudSettingsWidget.setTitle(_translate("CloudSettingsWidget", "Settings"))
        self.sync_label.setText(_translate("CloudSettingsWidget", "Enable sync"))
        self.path_label.setText(_translate("CloudSettingsWidget", "Saves path"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CloudSettingsWidget = QtWidgets.QGroupBox()
    ui = Ui_CloudSettingsWidget()
    ui.setupUi(CloudSettingsWidget)
    CloudSettingsWidget.show()
    sys.exit(app.exec_())
