# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rare/ui/components/tabs/games/game_info/game_dlc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameDlc(object):
    def setupUi(self, GameDlc):
        GameDlc.setObjectName("GameDlc")
        GameDlc.resize(650, 518)
        GameDlc.setWindowTitle("GameDlc")
        self.game_dlc_layout = QtWidgets.QVBoxLayout(GameDlc)
        self.game_dlc_layout.setObjectName("game_dlc_layout")
        self.noborder = QtWidgets.QScrollArea(GameDlc)
        self.noborder.setWidgetResizable(True)
        self.noborder.setObjectName("noborder")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 630, 245))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.game_title = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_title.sizePolicy().hasHeightForWidth())
        self.game_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.game_title.setFont(font)
        self.game_title.setText("error")
        self.game_title.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse | QtCore.Qt.TextSelectableByMouse)
        self.game_title.setObjectName("game_title")
        self.verticalLayout.addWidget(self.game_title)
        self.available_dlc_group = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.available_dlc_group.sizePolicy().hasHeightForWidth())
        self.available_dlc_group.setSizePolicy(sizePolicy)
        self.available_dlc_group.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.available_dlc_group.setObjectName("available_dlc_group")
        self.available_dlc_group_layout = QtWidgets.QVBoxLayout(self.available_dlc_group)
        self.available_dlc_group_layout.setObjectName("available_dlc_group_layout")
        self.available_dlc_label = QtWidgets.QLabel(self.available_dlc_group)
        self.available_dlc_label.setObjectName("available_dlc_label")
        self.available_dlc_group_layout.addWidget(self.available_dlc_label)
        self.verticalLayout.addWidget(self.available_dlc_group)
        self.installed_dlc_group = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.installed_dlc_group.sizePolicy().hasHeightForWidth())
        self.installed_dlc_group.setSizePolicy(sizePolicy)
        self.installed_dlc_group.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.installed_dlc_group.setObjectName("installed_dlc_group")
        self.installed_dlc_group_layout = QtWidgets.QVBoxLayout(self.installed_dlc_group)
        self.installed_dlc_group_layout.setObjectName("installed_dlc_group_layout")
        self.installed_dlc_label = QtWidgets.QLabel(self.installed_dlc_group)
        self.installed_dlc_label.setObjectName("installed_dlc_label")
        self.installed_dlc_group_layout.addWidget(self.installed_dlc_label)
        self.verticalLayout.addWidget(self.installed_dlc_group)
        self.noborder.setWidget(self.scrollAreaWidgetContents)
        self.game_dlc_layout.addWidget(self.noborder)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.game_dlc_layout.addItem(spacerItem)

        self.retranslateUi(GameDlc)
        QtCore.QMetaObject.connectSlotsByName(GameDlc)

    def retranslateUi(self, GameDlc):
        _translate = QtCore.QCoreApplication.translate
        self.available_dlc_group.setTitle(_translate("GameDlc", "Available DLCs"))
        self.available_dlc_label.setText(_translate("GameDlc", "No Downloadable Content is available"))
        self.installed_dlc_group.setTitle(_translate("GameDlc", "Installed DLCs"))
        self.installed_dlc_label.setText(_translate("GameDlc", "No Downloadable Content has been installed."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GameDlc = QtWidgets.QWidget()
    ui = Ui_GameDlc()
    ui.setupUi(GameDlc)
    GameDlc.show()
    sys.exit(app.exec_())
