# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/utils/pathedit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PathEdit(object):
    def setupUi(self, PathEdit):
        PathEdit.setObjectName("PathEdit")
        PathEdit.resize(407, 182)
        self.gridLayout = QtWidgets.QGridLayout(PathEdit)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.path_select = QtWidgets.QToolButton(PathEdit)
        self.path_select.setObjectName("path_select")
        self.gridLayout.addWidget(self.path_select, 1, 2, 1, 1)
        self.text_edit = QtWidgets.QLineEdit(PathEdit)
        self.text_edit.setObjectName("text_edit")
        self.gridLayout.addWidget(self.text_edit, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.save_path_button = QtWidgets.QPushButton(PathEdit)
        self.save_path_button.setEnabled(True)
        self.save_path_button.setObjectName("save_path_button")
        self.gridLayout.addWidget(self.save_path_button, 2, 1, 1, 2)

        self.retranslateUi(PathEdit)
        QtCore.QMetaObject.connectSlotsByName(PathEdit)

    def retranslateUi(self, PathEdit):
        _translate = QtCore.QCoreApplication.translate
        PathEdit.setWindowTitle(_translate("PathEdit", "PathEdit"))
        self.path_select.setText(_translate("PathEdit", "..."))
        self.save_path_button.setText(_translate("PathEdit", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PathEdit = QtWidgets.QWidget()
    ui = Ui_PathEdit()
    ui.setupUi(PathEdit)
    PathEdit.show()
    sys.exit(app.exec_())
