name: 'Python Setup'
description: 'Installs Python with sensible default values'
inputs:
  architecture:
    description: "The architecture of Python to set up"
    default: ${{ runner.arch }}
  version:
    description: "The version of Python to set up"
    default: '3.13'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v7
      with:
        cache: pip
        python-version: ${{ inputs.version }}
        check-latest: true
        architecture: ${{ inputs.architecture }}
