name: 'Python Setup'
description: 'Installs Python with sensible default values'
inputs:
  architecture:
    description: "The architecture of Python to set up"
    default: ${{ runner.arch }}
  version:
    description: "The version of Python to set up"
    default: '3.13'
runs:
  using: 'composite'
  steps:
    - name: GH Actions silliness (please add lower)
      id: silly
      shell: bash
      run: |
         echo "pyarch=$(echo ${{ inputs.architecture }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
    - uses: actions/setup-python@v7
      with:
        cache: pip
        python-version: ${{ inputs.version }}
        check-latest: true
        architecture: ${{ steps.silly.outputs.pyarch }}
