# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rare/ui/components/tabs/settings/game_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameSettings(object):
    def setupUi(self, GameSettings):
        GameSettings.setObjectName("GameSettings")
        GameSettings.resize(393, 202)
        self.main_layout = QtWidgets.QVBoxLayout(GameSettings)
        self.main_layout.setObjectName("main_layout")
        self.launch_settings_group = QtWidgets.QGroupBox(GameSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.launch_settings_group.sizePolicy().hasHeightForWidth())
        self.launch_settings_group.setSizePolicy(sizePolicy)
        self.launch_settings_group.setObjectName("launch_settings_group")
        self.launch_layout = QtWidgets.QFormLayout(self.launch_settings_group)
        self.launch_layout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.launch_layout.setObjectName("launch_layout")
        self.skip_update_label = QtWidgets.QLabel(self.launch_settings_group)
        self.skip_update_label.setObjectName("skip_update_label")
        self.launch_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.skip_update_label)
        self.skip_update_combo = QtWidgets.QComboBox(self.launch_settings_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skip_update_combo.sizePolicy().hasHeightForWidth())
        self.skip_update_combo.setSizePolicy(sizePolicy)
        self.skip_update_combo.setObjectName("skip_update_combo")
        self.skip_update_combo.addItem("")
        self.skip_update_combo.addItem("")
        self.skip_update_combo.addItem("")
        self.launch_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.skip_update_combo)
        self.offline_label = QtWidgets.QLabel(self.launch_settings_group)
        self.offline_label.setObjectName("offline_label")
        self.launch_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.offline_label)
        self.offline_combo = QtWidgets.QComboBox(self.launch_settings_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offline_combo.sizePolicy().hasHeightForWidth())
        self.offline_combo.setSizePolicy(sizePolicy)
        self.offline_combo.setObjectName("offline_combo")
        self.offline_combo.addItem("")
        self.offline_combo.addItem("")
        self.offline_combo.addItem("")
        self.launch_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.offline_combo)
        self.launch_params_label = QtWidgets.QLabel(self.launch_settings_group)
        self.launch_params_label.setObjectName("launch_params_label")
        self.launch_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.launch_params_label)
        self.launch_params_edit = QtWidgets.QLineEdit(self.launch_settings_group)
        self.launch_params_edit.setObjectName("launch_params_edit")
        self.launch_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.launch_params_edit)
        self.pre_launch_label = QtWidgets.QLabel(self.launch_settings_group)
        self.pre_launch_label.setObjectName("pre_launch_label")
        self.launch_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pre_launch_label)
        self.override_exe_label = QtWidgets.QLabel(self.launch_settings_group)
        self.override_exe_label.setObjectName("override_exe_label")
        self.launch_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.override_exe_label)
        self.wrapper_label = QtWidgets.QLabel(self.launch_settings_group)
        self.wrapper_label.setObjectName("wrapper_label")
        self.launch_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.wrapper_label)
        self.main_layout.addWidget(self.launch_settings_group)

        self.retranslateUi(GameSettings)

    def retranslateUi(self, GameSettings):
        _translate = QtCore.QCoreApplication.translate
        GameSettings.setWindowTitle(_translate("GameSettings", "GameSettings"))
        self.launch_settings_group.setTitle(_translate("GameSettings", "Launch Settings"))
        self.skip_update_label.setText(_translate("GameSettings", "Skip update check"))
        self.skip_update_combo.setItemText(0, _translate("GameSettings", "Default"))
        self.skip_update_combo.setItemText(1, _translate("GameSettings", "Yes"))
        self.skip_update_combo.setItemText(2, _translate("GameSettings", "No"))
        self.offline_label.setText(_translate("GameSettings", "Offline mode"))
        self.offline_combo.setItemText(0, _translate("GameSettings", "Default"))
        self.offline_combo.setItemText(1, _translate("GameSettings", "Yes"))
        self.offline_combo.setItemText(2, _translate("GameSettings", "No"))
        self.launch_params_label.setText(_translate("GameSettings", "Launch parameters"))
        self.launch_params_edit.setPlaceholderText(_translate("GameSettings", "parameters"))
        self.pre_launch_label.setText(_translate("GameSettings", "Pre-launch command"))
        self.override_exe_label.setText(_translate("GameSettings", "Override executable"))
        self.wrapper_label.setText(_translate("GameSettings", "Wrappers"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GameSettings = QtWidgets.QWidget()
    ui = Ui_GameSettings()
    ui.setupUi(GameSettings)
    GameSettings.show()
    sys.exit(app.exec_())
