# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rare/ui/components/tabs/settings/wrapper.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WrapperSettings(object):
    def setupUi(self, WrapperSettings):
        WrapperSettings.setObjectName("WrapperSettings")
        WrapperSettings.resize(413, 106)
        self.horizontalLayout = QtWidgets.QHBoxLayout(WrapperSettings)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_stack = QtWidgets.QStackedWidget(WrapperSettings)
        self.widget_stack.setObjectName("widget_stack")
        self.placeholder = QtWidgets.QWidget()
        self.placeholder.setObjectName("placeholder")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.placeholder)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wrapper_scroll_area = QtWidgets.QScrollArea(self.placeholder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrapper_scroll_area.sizePolicy().hasHeightForWidth())
        self.wrapper_scroll_area.setSizePolicy(sizePolicy)
        self.wrapper_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.wrapper_scroll_area.setWidgetResizable(True)
        self.wrapper_scroll_area.setObjectName("wrapper_scroll_area")
        self.scroll_content = QtWidgets.QWidget()
        self.scroll_content.setGeometry(QtCore.QRect(0, 0, 286, 68))
        self.scroll_content.setObjectName("scroll_content")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scroll_content)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.wrapper_scroll_area.setWidget(self.scroll_content)
        self.horizontalLayout_2.addWidget(self.wrapper_scroll_area)
        self.widget_stack.addWidget(self.placeholder)
        self.label_page = QtWidgets.QWidget()
        self.label_page.setObjectName("label_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.label_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.no_wrapper_label = QtWidgets.QLabel(self.label_page)
        self.no_wrapper_label.setObjectName("no_wrapper_label")
        self.verticalLayout.addWidget(self.no_wrapper_label)
        self.widget_stack.addWidget(self.label_page)
        self.horizontalLayout.addWidget(self.widget_stack)
        self.add_button = QtWidgets.QPushButton(WrapperSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_button.sizePolicy().hasHeightForWidth())
        self.add_button.setSizePolicy(sizePolicy)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout.addWidget(self.add_button)

        self.retranslateUi(WrapperSettings)
        self.widget_stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WrapperSettings)

    def retranslateUi(self, WrapperSettings):
        _translate = QtCore.QCoreApplication.translate
        WrapperSettings.setWindowTitle(_translate("WrapperSettings", "Frame"))
        self.no_wrapper_label.setText(_translate("WrapperSettings", "No wrapper added"))
        self.add_button.setText(_translate("WrapperSettings", "Add Wrapper"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WrapperSettings = QtWidgets.QFrame()
    ui = Ui_WrapperSettings()
    ui.setupUi(WrapperSettings)
    WrapperSettings.show()
    sys.exit(app.exec_())
