# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rare/ui/components/tabs/games/integrations/eos_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EosWidget(object):
    def setupUi(self, EosWidget):
        EosWidget.setObjectName("EosWidget")
        EosWidget.resize(465, 98)
        EosWidget.setWindowTitle("GroupBox")
        self.eos_layout = QtWidgets.QVBoxLayout(EosWidget)
        self.eos_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.eos_layout.setObjectName("eos_layout")
        self.overlay_stack = QtWidgets.QStackedWidget(EosWidget)
        self.overlay_stack.setObjectName("overlay_stack")
        self.install_page = QtWidgets.QWidget()
        self.install_page.setObjectName("install_page")
        self.install_page_layout = QtWidgets.QHBoxLayout(self.install_page)
        self.install_page_layout.setContentsMargins(0, 0, 0, 0)
        self.install_page_layout.setObjectName("install_page_layout")
        self.install_label_layout = QtWidgets.QFormLayout()
        self.install_label_layout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.install_label_layout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.install_label_layout.setObjectName("install_label_layout")
        self.install_label = QtWidgets.QLabel(self.install_page)
        self.install_label.setObjectName("install_label")
        self.install_label_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.install_label)
        self.install_text = QtWidgets.QLabel(self.install_page)
        self.install_text.setObjectName("install_text")
        self.install_label_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.install_text)
        self.install_page_layout.addLayout(self.install_label_layout)
        self.install_button_layout = QtWidgets.QVBoxLayout()
        self.install_button_layout.setContentsMargins(-1, -1, 0, -1)
        self.install_button_layout.setObjectName("install_button_layout")
        self.install_button = QtWidgets.QPushButton(self.install_page)
        self.install_button.setMinimumSize(QtCore.QSize(140, 0))
        self.install_button.setObjectName("install_button")
        self.install_button_layout.addWidget(self.install_button, 0, QtCore.Qt.AlignTop)
        self.install_page_layout.addLayout(self.install_button_layout)
        self.install_page_layout.setStretch(0, 1)
        self.overlay_stack.addWidget(self.install_page)
        self.info_page = QtWidgets.QWidget()
        self.info_page.setObjectName("info_page")
        self.info_page_layout = QtWidgets.QHBoxLayout(self.info_page)
        self.info_page_layout.setContentsMargins(0, 0, 0, 0)
        self.info_page_layout.setObjectName("info_page_layout")
        self.info_label_layout = QtWidgets.QFormLayout()
        self.info_label_layout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.info_label_layout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.info_label_layout.setObjectName("info_label_layout")
        self.version_label = QtWidgets.QLabel(self.info_page)
        self.version_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.version_label.setObjectName("version_label")
        self.info_label_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.version_label)
        self.path_label = QtWidgets.QLabel(self.info_page)
        self.path_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.path_label.setObjectName("path_label")
        self.info_label_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.path_label)
        self.info_page_layout.addLayout(self.info_label_layout)
        self.info_button_layout = QtWidgets.QVBoxLayout()
        self.info_button_layout.setObjectName("info_button_layout")
        self.update_button = QtWidgets.QPushButton(self.info_page)
        self.update_button.setMinimumSize(QtCore.QSize(140, 0))
        self.update_button.setObjectName("update_button")
        self.info_button_layout.addWidget(self.update_button, 0, QtCore.Qt.AlignTop)
        self.uninstall_button = QtWidgets.QPushButton(self.info_page)
        self.uninstall_button.setMinimumSize(QtCore.QSize(140, 0))
        self.uninstall_button.setObjectName("uninstall_button")
        self.info_button_layout.addWidget(self.uninstall_button, 0, QtCore.Qt.AlignTop)
        self.info_page_layout.addLayout(self.info_button_layout)
        self.info_page_layout.setStretch(0, 1)
        self.overlay_stack.addWidget(self.info_page)
        self.eos_layout.addWidget(self.overlay_stack)

        self.retranslateUi(EosWidget)
        self.overlay_stack.setCurrentIndex(0)

    def retranslateUi(self, EosWidget):
        _translate = QtCore.QCoreApplication.translate
        EosWidget.setTitle(_translate("EosWidget", "Epic Overlay"))
        self.install_label.setText(_translate("EosWidget", "Version"))
        self.install_text.setText(_translate("EosWidget", "Epic Online Services Overlay is not installed"))
        self.install_button.setText(_translate("EosWidget", "Install"))
        self.version_label.setText(_translate("EosWidget", "Version"))
        self.path_label.setText(_translate("EosWidget", "Install folder"))
        self.update_button.setText(_translate("EosWidget", "Update"))
        self.uninstall_button.setText(_translate("EosWidget", "Uninstall"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EosWidget = QtWidgets.QGroupBox()
    ui = Ui_EosWidget()
    ui.setupUi(EosWidget)
    EosWidget.show()
    sys.exit(app.exec_())
