# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rare/ui/components/tabs/settings/widgets/discord_rpc.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DiscordRPCSettings(object):
    def setupUi(self, DiscordRPCSettings):
        DiscordRPCSettings.setObjectName("DiscordRPCSettings")
        DiscordRPCSettings.resize(370, 149)
        DiscordRPCSettings.setWindowTitle("DiscordRPCSettings")
        self.main_layout = QtWidgets.QGridLayout(DiscordRPCSettings)
        self.main_layout.setObjectName("main_layout")
        self.enable = QtWidgets.QComboBox(DiscordRPCSettings)
        self.enable.setObjectName("enable")
        self.enable.addItem("")
        self.enable.addItem("")
        self.enable.addItem("")
        self.main_layout.addWidget(self.enable, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(DiscordRPCSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.main_layout.addWidget(self.label, 0, 0, 1, 1)
        self.show_game = QtWidgets.QCheckBox(DiscordRPCSettings)
        self.show_game.setObjectName("show_game")
        self.main_layout.addWidget(self.show_game, 1, 0, 1, 2)
        self.show_os = QtWidgets.QCheckBox(DiscordRPCSettings)
        self.show_os.setObjectName("show_os")
        self.main_layout.addWidget(self.show_os, 2, 0, 1, 2)
        self.show_time = QtWidgets.QCheckBox(DiscordRPCSettings)
        self.show_time.setObjectName("show_time")
        self.main_layout.addWidget(self.show_time, 3, 0, 1, 2)

        self.retranslateUi(DiscordRPCSettings)

    def retranslateUi(self, DiscordRPCSettings):
        _translate = QtCore.QCoreApplication.translate
        DiscordRPCSettings.setTitle(_translate("DiscordRPCSettings", "Discord RPC"))
        self.enable.setItemText(0, _translate("DiscordRPCSettings", "When Playing"))
        self.enable.setItemText(1, _translate("DiscordRPCSettings", "Always"))
        self.enable.setItemText(2, _translate("DiscordRPCSettings", "Never"))
        self.label.setText(_translate("DiscordRPCSettings", "Show"))
        self.show_game.setText(_translate("DiscordRPCSettings", "Show Game"))
        self.show_os.setText(_translate("DiscordRPCSettings", "Show OS"))
        self.show_time.setText(_translate("DiscordRPCSettings", "Show Time playing"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DiscordRPCSettings = QtWidgets.QGroupBox()
    ui = Ui_DiscordRPCSettings()
    ui.setupUi(DiscordRPCSettings)
    DiscordRPCSettings.show()
    sys.exit(app.exec_())
