# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rare/ui/components/tabs/settings/wine.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WineSettings(object):
    def setupUi(self, WineSettings):
        WineSettings.setObjectName("WineSettings")
        WineSettings.resize(104, 72)
        WineSettings.setWindowTitle("WIneSettings")
        self.main_layout = QtWidgets.QFormLayout(WineSettings)
        self.main_layout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.main_layout.setObjectName("main_layout")
        self.prefix_label = QtWidgets.QLabel(WineSettings)
        self.prefix_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prefix_label.setObjectName("prefix_label")
        self.main_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.prefix_label)
        self.exec_label = QtWidgets.QLabel(WineSettings)
        self.exec_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.exec_label.setObjectName("exec_label")
        self.main_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.exec_label)

        self.retranslateUi(WineSettings)

    def retranslateUi(self, WineSettings):
        _translate = QtCore.QCoreApplication.translate
        WineSettings.setTitle(_translate("WineSettings", "Wine Settings"))
        self.prefix_label.setText(_translate("WineSettings", "Prefix"))
        self.exec_label.setText(_translate("WineSettings", "Executable"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WineSettings = QtWidgets.QGroupBox()
    ui = Ui_WineSettings()
    ui.setupUi(WineSettings)
    WineSettings.show()
    sys.exit(app.exec_())
