# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rare/ui/components/dialogs/login/import_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImportLogin(object):
    def setupUi(self, ImportLogin):
        ImportLogin.setObjectName("ImportLogin")
        ImportLogin.resize(480, 180)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ImportLogin.sizePolicy().hasHeightForWidth())
        ImportLogin.setSizePolicy(sizePolicy)
        ImportLogin.setMinimumSize(QtCore.QSize(480, 180))
        ImportLogin.setWindowTitle("ImportLogin")
        self.import_layout = QtWidgets.QFormLayout(ImportLogin)
        self.import_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.import_layout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.import_layout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.import_layout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.import_layout.setObjectName("import_layout")
        self.title_label = QtWidgets.QLabel(ImportLogin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.import_layout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.title_label)
        self.prefix_label = QtWidgets.QLabel(ImportLogin)
        self.prefix_label.setObjectName("prefix_label")
        self.import_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.prefix_label)
        self.prefix_layout = QtWidgets.QHBoxLayout()
        self.prefix_layout.setObjectName("prefix_layout")
        self.prefix_combo = QtWidgets.QComboBox(ImportLogin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prefix_combo.sizePolicy().hasHeightForWidth())
        self.prefix_combo.setSizePolicy(sizePolicy)
        self.prefix_combo.setEditable(True)
        self.prefix_combo.setObjectName("prefix_combo")
        self.prefix_layout.addWidget(self.prefix_combo)
        self.prefix_tool = QtWidgets.QToolButton(ImportLogin)
        self.prefix_tool.setObjectName("prefix_tool")
        self.prefix_layout.addWidget(self.prefix_tool)
        self.import_layout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.prefix_layout)
        self.status_label = QtWidgets.QLabel(ImportLogin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.status_label.setFont(font)
        self.status_label.setText("")
        self.status_label.setWordWrap(True)
        self.status_label.setObjectName("status_label")
        self.import_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.status_label)
        self.info_label = QtWidgets.QLabel(ImportLogin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_label.sizePolicy().hasHeightForWidth())
        self.info_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.info_label.setFont(font)
        self.info_label.setWordWrap(True)
        self.info_label.setObjectName("info_label")
        self.import_layout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.info_label)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.import_layout.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem)

        self.retranslateUi(ImportLogin)

    def retranslateUi(self, ImportLogin):
        _translate = QtCore.QCoreApplication.translate
        self.title_label.setText(_translate("ImportLogin", "Import existing session from EGL"))
        self.prefix_label.setText(_translate("ImportLogin", "Select prefix"))
        self.prefix_tool.setText(_translate("ImportLogin", "Browse"))
        self.info_label.setText(_translate("ImportLogin", "You will get logged out from EGL in the process."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ImportLogin = QtWidgets.QWidget()
    ui = Ui_ImportLogin()
    ui.setupUi(ImportLogin)
    ImportLogin.show()
    sys.exit(app.exec_())
