# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'import_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImportLogin(object):
    def setupUi(self, ImportLogin):
        ImportLogin.setObjectName("ImportLogin")
        ImportLogin.resize(503, 173)
        ImportLogin.setWindowTitle("ImportLogin")
        self.import_layout = QtWidgets.QGridLayout(ImportLogin)
        self.import_layout.setObjectName("import_layout")
        self.info_label = QtWidgets.QLabel(ImportLogin)
        font = QtGui.QFont()
        font.setItalic(True)
        self.info_label.setFont(font)
        self.info_label.setWordWrap(True)
        self.info_label.setObjectName("info_label")
        self.import_layout.addWidget(self.info_label, 3, 0, 1, 3, QtCore.Qt.AlignBottom)
        self.title_label = QtWidgets.QLabel(ImportLogin)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.import_layout.addWidget(self.title_label, 0, 0, 1, 3, QtCore.Qt.AlignTop)
        self.prefix_combo = QtWidgets.QComboBox(ImportLogin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prefix_combo.sizePolicy().hasHeightForWidth())
        self.prefix_combo.setSizePolicy(sizePolicy)
        self.prefix_combo.setEditable(True)
        self.prefix_combo.setObjectName("prefix_combo")
        self.import_layout.addWidget(self.prefix_combo, 1, 1, 1, 1)
        self.prefix_label = QtWidgets.QLabel(ImportLogin)
        self.prefix_label.setObjectName("prefix_label")
        self.import_layout.addWidget(self.prefix_label, 1, 0, 1, 1)
        self.prefix_tool = QtWidgets.QToolButton(ImportLogin)
        self.prefix_tool.setObjectName("prefix_tool")
        self.import_layout.addWidget(self.prefix_tool, 1, 2, 1, 1)
        self.status_label = QtWidgets.QLabel(ImportLogin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.status_label.setFont(font)
        self.status_label.setText("")
        self.status_label.setObjectName("status_label")
        self.import_layout.addWidget(self.status_label, 2, 1, 1, 2)

        self.retranslateUi(ImportLogin)
        QtCore.QMetaObject.connectSlotsByName(ImportLogin)

    def retranslateUi(self, ImportLogin):
        _translate = QtCore.QCoreApplication.translate
        self.info_label.setText(_translate("ImportLogin", "You will get logged out from EGL in the process."))
        self.title_label.setText(_translate("ImportLogin", "Import existing session from EGL"))
        self.prefix_label.setText(_translate("ImportLogin", "Select path"))
        self.prefix_tool.setText(_translate("ImportLogin", "Browse"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ImportLogin = QtWidgets.QWidget()
    ui = Ui_ImportLogin()
    ui.setupUi(ImportLogin)
    ImportLogin.show()
    sys.exit(app.exec_())
