name: job_pypi

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install twine setuptools setuptools-scm
      - name: Build
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: ${{ inputs.version }}
        run: |
          python3 setup.py sdist bdist_wheel
      - name: Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/*
