name: job_ubuntu

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    name: Package
    runs-on: ubuntu-22.04
    container: ghcr.io/makedeb/makedeb:ubuntu-latest
    steps:
      - name: Prepare container
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get -y install git
      - name: Prepare source directory
        run: |
          sudo chown $(whoami) -R .
          sudo chmod 755 -R .
          git clone https://github.com/RareDevs/package-mpr.git build
          sed '/^pkgver=/d' -i build/PKGBUILD
          sed '/^source=/d' -i build/PKGBUILD
          echo "pkgver=${{ inputs.version }}" >> build/PKGBUILD
          echo "source=(\"git+https://github.com/${{ github.repository }}.git#branch=${{ github.ref_name }}\")" >> build/PKGBUILD
      - name: Run makedeb
        run: |
          cd build
          makedeb -s
          mv *.deb ../Rare.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rare-${{ inputs.version }}.deb
          path: Rare.deb
