name: job_cx-freeze-appimage

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    name: Package
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install patchelf fakeroot
      - uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: '3.12'
          check-latest: true
          architecture: x64
      - name: Install build dependencies
        run: |
          pip3 install --upgrade cx_freeze
      - name: Install target dependencies
        run: |
          pip3 install -r misc/requirements.in
      - name: Generate version information
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: ${{ inputs.version }}
        run: |
          python3 -m setuptools_scm --force-write-version-files
      - name: Build
        run: |
          python3 freeze.py bdist_appimage
          mv dist/Rare-*.AppImage Rare-${{ inputs.version }}.AppImage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rare-${{ inputs.version }}.AppImage
          path: Rare-${{ inputs.version }}.AppImage
