name: job_cx-freeze-macos

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: "arm64"
            pyarch: "arm64"
          - arch: "x86_64"
            pyarch: "x64"
    name: Package ${{ matrix.arch }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: '3.13'
          check-latest: true
          architecture: ${{ matrix.pyarch }}
      - name: Install Build Dependencies
        run: |
          pip3 install --upgrade cx_freeze
          git clone https://github.com/create-dmg/create-dmg
      - name: Install Target Dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install -r requirements-presence.txt
      - name: Build
        run: >-
          arch -${{ matrix.arch }}
          python freeze.py bdist_mac
      - name: Create dmg
        run: >-
          create-dmg/create-dmg
          Rare-${{ matrix.arch }}.dmg
          dist/Rare-*.App
          --volname Rare
          --volicon rare/resources/images/Rare.icns

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rare-${{ matrix.arch }}-${{ inputs.version }}.dmg
          path: Rare-${{ matrix.arch }}.dmg
