name: job_cx-freeze-macos

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    name: Package
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: '3.12'
          check-latest: true
          architecture: x64
      - name: Install Build Dependencies
        run: |
          pip3 install --upgrade cx_freeze
          git clone https://github.com/create-dmg/create-dmg
      - name: Install Target Dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install -r requirements-presence.txt
      - name: Build
        run: |
          python freeze.py bdist_mac
      - name: Create dmg
        run: >-
          create-dmg/create-dmg
          Rare.dmg
          build/Rare.app
          --volname Rare
          --volicon rare/resources/images/Rare.icns

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rare-${{ inputs.version }}.dmg
          path: Rare.dmg
