name: job_cx-freeze-macos

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
            pyarch: arm64
            os: macos-14
          - arch: x86_64
            pyarch: x64
            os: macos-13
    name: Package ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: '3.12'
          check-latest: true
          architecture: ${{ matrix.pyarch }}
      - name: Install build dependencies
        run: |
          pip3 install --upgrade cx_freeze
      - name: Install target dependencies
        run: |
          pip3 install -r misc/requirements.in
      - name: Generate version information
        run: |
          pip3 install setuptools-scm
          python3 -m setuptools_scm --force-write-version-files
      - name: Build
        run: |
          python3 freeze.py bdist_mac
      - name: Create dmg
        run: >-
          create-dmg/create-dmg
          Rare-${{ matrix.arch }}.dmg
          build/Rare.app
          --volname Rare
          --volicon rare/resources/images/Rare.icns

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rare-${{ matrix.arch }}-${{ inputs.version }}.dmg
          path: Rare-${{ matrix.arch }}.dmg
