name: job_cx-freeze-zip-win

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    name: Package
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: '3.12'
          check-latest: true
          architecture: x64
      - name: Install build dependencies
        run: pip3 install --upgrade cx_freeze
      - name: Install target dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install -r requirements-presence.txt
          pip3 install .
      - name: Build
        run: |
          python freeze.py build_exe
          mv dist/exe.* rare.dist
      - name: Compress
        run: |
          python -c "import shutil; shutil.make_archive('Rare', 'zip', 'rare.dist')"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rare-portable-windows-${{ inputs.version }}.zip
          path: Rare.zip

