
name: "Snapshot"


on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: "Create a pre-release"
        default: false
        required: true
        type: boolean
  pull_request:
    branches:
      - main
    types: [closed]


permissions:
  contents: write
  discussions: write


jobs:

  version:
    name: Describe
    uses: ./.github/workflows/job_version.yml

  title:
    needs: version
    name: Version ${{ needs.version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - run: "true"

  prerelease:
    if: ${{ inputs.prerelease }}
    needs: version
    name: Create pre-release
    runs-on: ubuntu-latest
    steps:
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ needs.version.outputs.version }}
        commit: "main"
        name: Pre-release ${{ needs.version.outputs.version }}
        draft: false
        prerelease: true
        generateReleaseNotes: true
        discussionCategory: "Releases"
        makeLatest: false

  ubuntu:
    needs: version
    name: Ubuntu
    uses: ./.github/workflows/job_ubuntu.yml
    with:
      version: ${{ needs.version.outputs.version }}
  ubuntu-release:
    if: ${{ inputs.prerelease }}
    needs: [version, prerelease, ubuntu]
    name: Ubuntu
    uses: ./.github/workflows/job_publish.yml
    with:
      version: ${{ needs.version.outputs.version }}
      file1: Rare.deb
      name1: Rare-${{ needs.version.outputs.version }}.deb

  appimage:
    needs: version
    name: AppImage
    uses: ./.github/workflows/job_appimage.yml
    with:
      version: ${{ needs.version.outputs.version }}
  appimage-release:
    if: ${{ inputs.prerelease }}
    needs: [version, prerelease, appimage]
    name: AppImage
    uses: ./.github/workflows/job_publish.yml
    with:
      version: ${{ needs.version.outputs.version }}
      file1: Rare.AppImage
      name1: Rare-${{ needs.version.outputs.version }}.AppImage
      file2: Rare.AppImage.zsync
      name2: Rare-${{ needs.version.outputs.version }}.AppImage.zsync

  nuitka-windows:
    if: ${{ true }}
    needs: version
    name: Nuitka Windows
    uses: ./.github/workflows/job_nuitka-win.yml
    with:
      version: ${{ needs.version.outputs.version }}
  nuitka-windows-release:
    if: ${{ inputs.prerelease }}
    needs: [version, prerelease, nuitka-windows]
    name: Nuitka Windows
    uses: ./.github/workflows/job_publish.yml
    with:
      version: ${{ needs.version.outputs.version }}
      file1: Rare.zip
      name1: Rare-portable-windows-${{ needs.version.outputs.version }}.zip

  nuitka-linux:
    if: ${{ true }}
    needs: version
    name: Nuitka Linux
    uses: ./.github/workflows/job_nuitka-linux.yml
    with:
      version: ${{ needs.version.outputs.version }}
  nuitka-linux-release:
    if: ${{ inputs.prerelease }}
    needs: [version, prerelease, nuitka-linux]
    name: Nuitka Linux
    uses: ./.github/workflows/job_publish.yml
    with:
      version: ${{ needs.version.outputs.version }}
      file1: Rare.zip
      name1: Rare-portable-linux-${{ needs.version.outputs.version }}.zip

  nuitka-macos:
    if: ${{ true }}
    needs: version
    name: Nuitka MacOS
    uses: ./.github/workflows/job_nuitka-macos.yml
    with:
      version: ${{ needs.version.outputs.version }}
  nuitka-macos-release:
    if: ${{ inputs.prerelease }}
    needs: [version, prerelease, nuitka-macos]
    name: Nuitka MacOS
    uses: ./.github/workflows/job_publish.yml
    with:
      version: ${{ needs.version.outputs.version }}
      file1: Rare-arm64.zip
      name1: Rare-portable-macos-arm64-${{ needs.version.outputs.version }}.zip
      file2: Rare-x86_64.zip
      name2: Rare-portable-macos-x86_64-${{ needs.version.outputs.version }}.zip

  cx-freeze-msi:
    needs: version
    name: cx-Freeze msi
    uses: ./.github/workflows/job_cx-freeze-msi.yml
    with:
      version: ${{ needs.version.outputs.version }}
  cx-freeze-msi-release:
    if: ${{ inputs.prerelease }}
    needs: [version, prerelease, cx-freeze-msi]
    name: cx-Freeze msi
    uses: ./.github/workflows/job_publish.yml
    with:
      version: ${{ needs.version.outputs.version }}
      file1: Rare.msi
      name1: Rare-${{ needs.version.outputs.version }}.msi

  cx-freeze-zip:
    if: ${{ false }}
    needs: version
    name: cx-Freeze zip
    uses: ./.github/workflows/job_cx-freeze-zip.yml
    with:
      version: ${{ needs.version.outputs.version }}
  cx-freeze-zip-release:
    if: ${{ inputs.prerelease }}
    needs: [version, prerelease, cx-freeze-zip]
    name: cx-Freeze zip
    uses: ./.github/workflows/job_publish.yml
    with:
      version: ${{ needs.version.outputs.version }}
      file1: Rare-portable-windows.zip
      name1: Rare-portable-windows-${{ needs.version.outputs.version }}.zip

  macos:
    needs: version
    name: macOS
    uses: ./.github/workflows/job_macos.yml
    with:
      version: ${{ needs.version.outputs.version }}
  macos-release:
    if: ${{ inputs.prerelease }}
    needs: [version, prerelease, macos]
    name: macOS
    uses: ./.github/workflows/job_publish.yml
    with:
      version: ${{ needs.version.outputs.version }}
      file1: Rare.dmg
      name1: Rare-${{ needs.version.outputs.version }}.dmg

