
name: "Snapshot"


on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: "Create a pre-release"
        default: false
        required: true
        type: boolean
  pull_request:
    branches:
      - main
    types: [closed]


permissions:
  contents: write
  discussions: write


jobs:

  version:
    name: Describe
    uses: ./.github/workflows/job_version.yml

  title:
    needs: version
    name: Version ${{ needs.version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - run: "true"

  prerelease:
    if: ${{ inputs.prerelease }}
    needs: version
    name: Create pre-release
    runs-on: ubuntu-latest
    steps:
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ needs.version.outputs.version }}
        commit: "main"
        name: Pre-release ${{ needs.version.outputs.version }}
        draft: false
        prerelease: true
        generateReleaseNotes: true
        discussionCategory: "Releases"
        makeLatest: true

  nuitka-linux:
    if: ${{ true }}
    needs: version
    name: Nuitka Linux
    uses: ./.github/workflows/job_nuitka-linux.yml
    with:
      version: ${{ needs.version.outputs.version }}
  nuitka-linux-release:
    if: ${{ inputs.prerelease }}
    needs: [version, prerelease, nuitka-linux]
    name: Nuitka Linux
    uses: ./.github/workflows/job_publish.yml
    with:
      version: ${{ needs.version.outputs.version }}
      file1: Rare.zip
      name1: Rare-linux-${{ needs.version.outputs.version }}.zip

  nuitka-macos:
    if: ${{ true }}
    needs: version
    name: Nuitka MacOS
    uses: ./.github/workflows/job_nuitka-macos.yml
    with:
      version: ${{ needs.version.outputs.version }}
  nuitka-macos-release:
    if: ${{ inputs.prerelease }}
    needs: [version, prerelease, nuitka-macos]
    name: Nuitka MacOS
    uses: ./.github/workflows/job_publish.yml
    with:
      version: ${{ needs.version.outputs.version }}
      file1: Rare-macos-arm64.app.zip
      name1: Rare-macos-arm64-${{ needs.version.outputs.version }}.app.zip
      file2: Rare-macos-x86_64.app.zip
      name2: Rare-macos-x86_64-${{ needs.version.outputs.version }}.app.zip

  nuitka-windows:
    if: ${{ true }}
    needs: version
    name: Nuitka Windows
    uses: ./.github/workflows/job_nuitka-windows.yml
    with:
      version: ${{ needs.version.outputs.version }}
  nuitka-windows-release:
    if: ${{ inputs.prerelease }}
    needs: [version, prerelease, nuitka-windows]
    name: Nuitka Windows
    uses: ./.github/workflows/job_publish.yml
    with:
      version: ${{ needs.version.outputs.version }}
      file1: Rare.zip
      name1: Rare-windows-${{ needs.version.outputs.version }}.zip

  cx-freeze-appimage:
    if: ${{ true }}
    needs: version
    name: cx-Freeze AppImage
    uses: ./.github/workflows/job_cx-freeze-appimage.yml
    with:
      version: ${{ needs.version.outputs.version }}
  cx-freeze-appimage-release:
    if: ${{ inputs.prerelease }}
    needs: [version, prerelease, cx-freeze-appimage]
    name: cx-Freeze AppImage
    uses: ./.github/workflows/job_publish.yml
    with:
      version: ${{ needs.version.outputs.version }}
      file1: Rare.Appimage
      name1: Rare-${{ needs.version.outputs.version }}.Appimage

  cx-freeze-dmg:
    if: ${{ true }}
    needs: version
    name: cx-Freeze MacOS
    uses: ./.github/workflows/job_cx-freeze-dmg.yml
    with:
      version: ${{ needs.version.outputs.version }}
  cx-freeze-dmg-release:
    if: ${{ inputs.prerelease }}
    needs: [version, prerelease, cx-freeze-dmg]
    name: cx-Freeze MacOS
    uses: ./.github/workflows/job_publish.yml
    with:
      version: ${{ needs.version.outputs.version }}
      file1: Rare-arm64.dmg
      name1: Rare-arm64-${{ needs.version.outputs.version }}.dmg
      file2: Rare-x86_64.dmg
      name2: Rare-x86_64-${{ needs.version.outputs.version }}.dmg

  cx-freeze-msi:
    if: ${{ true }}
    needs: version
    name: cx-Freeze MSI
    uses: ./.github/workflows/job_cx-freeze-msi.yml
    with:
      version: ${{ needs.version.outputs.version }}
  cx-freeze-msi-release:
    if: ${{ inputs.prerelease }}
    needs: [version, prerelease, cx-freeze-msi]
    name: cx-Freeze MSI
    uses: ./.github/workflows/job_publish.yml
    with:
      version: ${{ needs.version.outputs.version }}
      file1: Rare.msi
      name1: Rare-${{ needs.version.outputs.version }}.msi
