
name: "Snapshot"


on:
  pull_request:
    branches:
      - main
    types: [closed]


jobs:

  version:
    name: Describe
    uses: ./.github/workflows/job_version.yml

  title:
    needs: version
    name: Version ${{ needs.version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - run: "true"

  ubuntu:
    needs: version
    name: Ubuntu
    uses: ./.github/workflows/job_ubuntu.yml
    with:
      version: ${{ needs.version.outputs.version }}

  appimage:
    needs: version
    name: AppImage
    uses: ./.github/workflows/job_appimage.yml
    with:
      version: ${{ needs.version.outputs.version }}

  nuitka-win:
    if: ${{ false }}
    needs: version
    name: Nuitka Windows
    uses: ./.github/workflows/job_nuitka-win.yml
    with:
      version: ${{ needs.version.outputs.version }}

  cx-freeze-msi:
    needs: version
    name: cx-Freeze msi
    uses: ./.github/workflows/job_cx-freeze-msi.yml
    with:
      version: ${{ needs.version.outputs.version }}

  cx-freeze-zip:
    needs: version
    name: cx-Freeze zip
    uses: ./.github/workflows/job_cx-freeze-zip.yml
    with:
      version: ${{ needs.version.outputs.version }}

  macos:
    needs: version
    name: MacOS
    uses: ./.github/workflows/job_macos.yml
    with:
      version: ${{ needs.version.outputs.version }}

